### ISSUE TITLE
请教一个问题，感谢~

### ISSUE THREAD

**Issue by Yehnn** [itgoyo/itgoyo.github.io#3]
想请教一下为什么没有 _config.yml 文件，并且没有 themes 文件夹，如果 clone 到了本地，是怎么运行呢。感谢~

**Comment by itgoyo** [comment]
@Yehnn _config.yml这个东西一共有两个同名的，一个是在你hexo init 之后的博客源文件，一个是theme里面的主题，每一个主题都有相应的一个_config.yml，你确认你是不是已经hexo init过了

**Comment by itgoyo** [comment]
@Yehnn 这里有我几天前录制的一个视频关于如何搭建hexo博客的，你可以看一下，如果方便的话https://www.bilibili.com/video/av18024700/

**Comment by Yehnn** [comment]
@itgoyo 非常感谢~原来不能直接 clone 下来运行，这个不是源码。要自己重新搭建。
